name: OutputScan

# Controls when the workflow will run
on:
  push:
  pull_request:
    branches:
      - develop
      - staging
  workflow_dispatch:
jobs:
  OutputandExecutioncheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
