name: OutputScan

# Controls when the workflow will run
on:
  push:
  pull_request:
    branches:
      - develop
      - staging
  workflow_dispatch:
jobs:
  OutputandExecutioncheck:
    steps:
      - name: Run alert check to scan for outputs
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1