name: OutputScan

# Controls when the workflow will run
on:
  push:
  pull_request_target:
    branches:
      - develop
      - staging
  workflow_dispatch:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Ensure Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
            
