name: OutputScan

# Controls when the workflow will run
on:
  push:
  pull_request_target:
    branches:
      - develop
      - staging
  workflow_dispatch:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            jq --indent 1 '(.cells[] | select(has("outputs")) | .outputs) = [] | (.cells[] | select(has("execution_count")) | .execution_count) = null | .metadata = {"language_info": {"name":"python", "pygments_lexer": "ipython3"}} | .cells[].metadata = {}' Enron_Query_Elasticsearch-1-1.ipynb
        shell: bash
