name: OutputScan

# Controls when the workflow will run
on:
  push:
  pull_request_target:
    branches:
      - develop
      - staging
  workflow_dispatch:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            pip install jupyter nbconvert
      - name: Clear all outputs cells
        run: jq '.cells[].outputs = [] | .cells[].execution_count = null | .'" Enron_Query_Elasticsearch-1-1.ipynb
        shell: bash
            
