name: OutputScan

# Controls when the workflow will run
on:
  push:
  pull_request_target:
    branches:
      - develop
      - staging
  workflow_dispatch:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Setup python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Jupyter notebook installs
        run: pip install jupyterlab
      - name: Clear all outputs cells
        run: jupyter nbconvert --clear-output --inplace Enron_Query_Elasticsearch-1-1.ipynb
        shell: bash
            
